# Original maximum magnification
MAGNIFICATION = 40
MAGNIFICATION_20 = 20

# Downsample from magnification
DOWNSAMPLE_FACTOR_TISSUE = 32
DOWNSAMPLE_FACTOR_CMC_CZI = 32
DOWNSAMPLE_FACTOR_CMC = 16
DOWNSAMPLE_FACTOR_CMC_20 = 8
DOWNSAMPLE_FACTOR_CMC_VS = 8
DOWNSAMPLE_FACTOR_GAA_CZI = 8
DOWNSAMPLE_FACTOR_GAA = 4
DOWNSAMPLE_FACTOR_GAA_20 = 2
DOWNSAMPLE_FACTOR_GAA_VS = 2
DOWNSAMPLE_FACTOR_MAX = 1

# Desired Objective Power
DESIRED_OP_TISSUE = 1.25
DESIRED_OP_CMC_CZI = 1.25
DESIRED_OP_CMC = 2.5
DESIRED_OP_CMC_VS = 5
DESIRED_OP_GAA_CZI = 5
DESIRED_OP_GAA = 10
DESIRED_OP_GAA_VS = 20
DESIRED_OP_MAX = 40
